# Dependencies
markdown:             kramdown
highlighter:          rouge


# Gems
gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-seo-tag


# Settings
exclude:              [CNAME, README.md, NOTES.md, LICENSE.md, .gitignore, package.json, bower.json, _js, _scss, _images, gulpfile.js, gulpconfig.js, node_modules, bower_components, gemfile, Gemfile.lock]
permalink:            /:title/
compress_html:
  clippings: all
  comments: all


# Site meta
title:                'DH-WOGEM'
tagline:              'Women and Gender Minorities in Digital Humanities'
description:          'Homepage for a group supporting and advocating for women and gender minorities in Digital Humanities'
url:                  https://madebyconnor.github.io
baseurl:              /change
assets:               /assets
images:               /images/
image:                index-large.jpg
logo:                 /assets/icons/apple-icon-144x144.png
dark_theme:           false


version:              3.1.3

github:
  repo:               https://github.com/dh-wogem/dh-wogem.github.io


# Integrations
# typekit:              fcv7rfe

google_fonts:
  Overpass:           400, 600, 800

# google_analytics_key: UA-94021817-2
# google_site_verification: Z-pc_HPc4XNBz8xg1fgtxO2MSIYLirZc2jWTNq0bJyM


# Content
excerpt_separator: <!-- Read more -->

